FROM microsoft/dotnet:2.2-sdk
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["identity.api/identity.api.csproj", "identity.api/"]

RUN dotnet restore "identity.api/identity.api.csproj"
COPY . .
WORKDIR "/src/identity.api"
RUN dotnet build --no-restore "identity.api.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]